notifications:
  email: false
  irc:
    channels:
      - "ircs://irc.hackint.org:6697/#dtn7"
    template:
      - "[%{repository_name}] %{author}, %{commit}@%{branch}: %{message} "
    on_success: change
    on_failure: always

language: go

go:
  - 1.11.x
  - 1.x

env:
  - GO111MODULE=on

git:
  depth: 1

install: true

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin

script:
  - go build ./...
  - gofmt -l -e -d .
  - go vet ./...
  - golangci-lint run -v ./...
  - go test -v -race ./...
