notifications:
  email: false
  irc:
    channels:
      - "ircs://irc.hackint.org:6697/#dtn7"
    template:
      - "[%{repository_name}] %{author}, %{commit}@%{branch}: %{message} "
    use_notice: true

language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

env:
  - GO111MODULE=on

git:
  depth: 1

install: true

script:
  - gofmt -l -e -d .
  - go build ./...
  - go vet ./...
  - go test -v -race ./...
