[core]
store = "store.dat"

[simple-rest]
node = "dtn:sender"
listen = "127.0.0.1:8080"

[[listen]]
node = "dtn:hostymyhostface"
protocol = "stcp"
endpoint = "0.0.0.0:35037"

[[peer]]
node = "dtn:alpha"
protocol = "stcp"
endpoint = "10.0.0.2:35037"

[[peer]]
node = "dtn:beta"
protocol = "stcp"
endpoint = "[fc23::2]:35037"
