# SPDX-FileCopyrightText: 2020 Alvar Penning
#
# SPDX-License-Identifier: GPL-3.0-or-later

issues:
  exclude-rules:
    # Don't calculate the cyclomatic complexity for tests
    - path: _test\.go
      linters:
        - gocyclo
    # Some deterministic "pseudo random" data is needed in tests
    - path: _test\.go
      text: "G404:"
      linters:
        - gosec
    # Allow dynamic URLs
    - linters:
        - gosec
      text: "G107:"

linters:
  # In addition to the default
  enable:
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - prealloc
    - unconvert
