# SPDX-FileCopyrightText: 2020 Alvar Penning
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: REUSE Compliance Check

on: [push, pull_request]

jobs:
  reuse_check:
    name: REUSE Compliance Check

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@43bd643263f2a557a37e023e538ab9f83dce92a6  # v1.1
