# SPDX-FileCopyrightText: 2020 Alvar Penning
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Check golangci-lint

on: [push, pull_request]

jobs:
  golangci:
    name: Check golangci-lint

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@6317259e28065ecd33bf7e7e6c67c77db091d8a4  # v2.2.0
      with:
        version: v1.30

