# SPDX-FileCopyrightText: 2020, 2021 Alvar Penning
# SPDX-FileCopyrightText: 2022, 2023 Markus Sommer
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on: [push, pull_request]

jobs:
  golang:
    name: Build and test dtn7-go

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.19', '1.20' ]

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build on Go ${{ matrix.go }}
      run: go build ./...

    - name: Test
      run: go test -race -p 1 ./...


  golangci:
    name: Check golangci-lint

    runs-on: ubuntu-latest

    steps:
    - name: Setup linter
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Check out code
      uses: actions/checkout@v3

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.51.2
        args: --config contrib/golangci-lint/.golangci.yml


  reuse:
    name: Check REUSE compliance

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1.2.0
