# SPDX-FileCopyrightText: 2019, 2020, 2021 Alvar Penning
# SPDX-FileCopyrightText: 2021 Artur Sterz
# SPDX-FileCopyrightText: 2021 Jonas Höchst
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Run extended tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Send repository_dispatch event to dtn7-playground repo
      run: |
        curl -XPOST -u "${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/dtn7/dtn7-playground/dispatches --data '{"event_type": "run"}'
