# SPDX-FileCopyrightText: 2020 Alvar Penning
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Nightly Tests

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  golang:
    name: Build and test dtn7-go

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.13', '1.15' ]

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build on Go ${{ matrix.go }}
      run: go build  ./...

    - name: Test
      run: go test -race ./...
